***
# **<center>Bilans</center>**
***

<div style="background-color: yellow; padding: 10px;">
<h1 style="background-color: yellow;">1- Bilan1</h1>
</div>


### 1-1- Question2

Le code est-il correct?

In [10]:
nombre = 24
texte1 = 'Nous sommes'
texte2 = 'étudiants'
print("%d Aujourd'hui %s" % (texte1, nombre))

TypeError: %d format: a real number is required, not str

**NON**  le La chaine de caractères(%s) et l'entier (%d) ont été inversés.

In [11]:
nombre = 24
texte = 'Nous sommes'
print("%s %d étudiants" % (texte, nombre))

Nous sommes 24 étudiants


### 1-2- Question3

Ce code va afficher tous les nombre impairs

In [12]:
liste = [0, 1, 2 ,3 , 4, 5, 6, 7, 8]
print(liste[7::-2])

[7, 5, 3, 1]


**OUI** on commence à l'indice 7 inclus et on prend 1 indice sur 2 dans l'ordre décroissant

### 1-3- Question4

Ce code va afficher 1 3 5 7

In [13]:
for i in liste[7::-2]:
    print(i)

7
5
3
1


**NON** l'ordre est décroissant car le dernier indice est négatif

<div style="background-color: yellow; padding: 10px;">
<h1 style="background-color: yellow;">2- Bilan2</h1>
</div>

### 2-1 Question2

la fonction définie par:
```python
 def faire_une_action(*args):
```
Accepte un nombre variable de paramètres

**OUI** Le * devant args indique que cette fonction peut accepter un nombre variable d'arguments, qui seront rassemblés dans un tuple nommé args. 

### 2-2 Question3

```python
a = 1 
def ma_fonction():
    b = 2 
```

### 2-3 Question4

```python
from a import b
```

a est un nom de fonction  
b est un nom de fichier

**NON** a est nom de fichier et b un nom de fonction

### 2-3 Question5

Matplotlib permet des représentations en echelle logarithmique

**OUI** Avec 
```python
ax.set_yscale('log')
```
ou
```python
ax.set_xscale('log')
```

<div style="background-color: yellow; padding: 10px;">
<h1 style="background-color: yellow;">3- Bilan3</h1>
</div>

# 3-1 Question2

In [14]:
import numpy as np

- Le code suivant affichera (3,2)

In [15]:
a = np.array([[5, 6, 3],[7, 8, 5]])
print(a.shape)

(2, 3)


**Non** l'odre est ligne colonne et non colonne ligne

### 3-2 Question3

- Le code suivant affiche True

In [16]:
a = np.zeros((3, 2))
b = np.array([[5, 6, 3],[7, 8, 5]])
if a.ndim == b.ndim:
    print(True)
else:
    print(False)

print(a)
print(a.ndim)
print('---------')
print(b)
print(b.ndim)

True
[[0. 0.]
 [0. 0.]
 [0. 0.]]
2
---------
[[5 6 3]
 [7 8 5]]
2


**OUI** Il y a bien le meme nombre de dimensions 

### 3-3 Question4

- Le code suivant donnera 5

In [17]:
a = np.array([[5, 6, 3],[7, 8, 5]])
print(a[1,1])

8


**Non** il affichera l'élément de la ligne 1 colonne 1 (5 est l'élément en ligne 0 colonne 0)

### 3-4 Question5

In [18]:
import math

In [19]:
a = np.array([math.pi, math.pi/2, math.pi/4])

- Pour obtenir un tableau contenant le sinus des éléments du tableau a il faut faire:

In [20]:
print(np.sin(a))
print(math.sin(a))

[1.22464680e-16 1.00000000e+00 7.07106781e-01]


TypeError: only length-1 arrays can be converted to Python scalars

Il faut faire print(math.sin(a)) pour calcluler le sinus des éléments d'un tableau. Math.sin attend un nombre en argument et non un tableau.

<div style="background-color: yellow; padding: 10px;">
<h1 style="background-color: yellow;">4- Bilan4</h1>
</div>

### 4-1 Question2

In [2]:
import pandas as pd

In [3]:
data = {
    "Sex": ['M', 'F', 'M', 'F', 'M'],
    "Age": [24, 32, 28, 29, 35],
    "Weight": [75, 62, 80, 55, 70],
    "Height": [180, 165.5, 175, 170.3, 185.6]  # Tailles en cm, certains en int, d'autres en float
}

df = pd.DataFrame(data)

Le tableau est obtenu avec **df.describe()**

In [4]:
df.describe()

Age     Weight      Height
count   5.000000   5.000000    5.000000
mean   29.600000  68.400000  175.280000
std     4.159327  10.014989    7.894745
min    24.000000  55.000000  165.500000
25%    28.000000  62.000000  170.300000
50%    29.000000  70.000000  175.000000
75%    32.000000  75.000000  180.000000
max    35.000000  80.000000  185.600000

### 4-2 Question3

In [5]:
import pandas as pd
df = pd.read_csv('fichier_exercices_enonces/7_pandas/heart.csv')
df_hommes_jeunes = df.query("age < 35 & sex == 1")
if df_hommes_jeunes.shape == df.shape:
    print('Même dimension')
else:
    print('Dimension différente')

Dimension différente


**Dimension différente** contrairement à df.where, df.query ne conserve pas le dimensions du datframe 

In [6]:
print(df.shape)
print(df_hommes_jeunes.shape)

(303, 14)
(2, 14)


### 4-3 Question4

Pour écrire de nouvelles données après des données existantes on utilisera la syntaxe:

In [7]:
#Mauvaise réponse, on efface le contenu eventuel du fichier
with open('mon_fichier.txt', 'w') as fichier:
    fichier.write('Nouvelles donnees')

In [8]:
#Bonne réponse le mode append permet d'ajouter des données à la suite
with open('mon_fichier.txt', 'a') as fichier:
    fichier.write('Nouvelles donnees')

In [11]:
#Mauvaise réponse en mode leccture on ne peut pas ecrire
with open('mon_fichier.txt', 'r') as fichier:
    fichier.write('Nouvelles donnees')

UnsupportedOperation: not writable

In [10]:
#Mauvaise réponse, le mode p n'existe pas
with open('mon_fichier.txt', 'p') as fichier:
    fichier.write('Nouvelles donnees')

ValueError: invalid mode: 'p'

### 4-4 Question5

In [44]:
chemin = 'fichier_exercices_enonces/8_fichiers/E15_bis.xy'
with open(chemin, 'r') as fichier:
    lignes = fichier.readlines()

print(type(lignes))

<class 'list'>
